const config = {
  accountLanguages: {
    arabic: 'Arabic',
    bulgarian: 'Bulgarian',
    schinese: 'Chinese (Simplified)',
    tchinese: 'Chinese (Traditional)',
    czech: 'Czech',
    danish: 'Danish',
    dutch: 'Dutch',
    english: 'English',
    finnish: 'Finnish',
    french: 'French',
    german: 'German',
    greek: 'Greek',
    hungarian: 'Hungarian',
    italian: 'Italian',
    japanese: 'Japanese',
    koreana: 'Korean',
    norwegian: 'Norwegian',
    polish: 'Polish',
    portuguese: 'Portuguese',
    brazilian: 'Portuguese-Brazil',
    romanian: 'Romanian',
    russian: 'Russian',
    spanish: 'Spanish-Spain',
    latam: 'Spanish-Latin America',
    swedish: 'Swedish',
    thai: 'Thai',
    turkish: 'Turkish',
    ukrainian: 'Ukrainian',
    vietnamese: 'Vietnamese',
  },
  allowedExtensions: ['.exe'],
};

export default config;
